language: php
php:
    - 5.4
    - 5.5
before_script:
    - ./scripts/init-dependencies.sh
script:
    - ./scripts/test-phpunit.sh
    - ./scripts/test-karma.sh
notifications:
    email:
        - fabio.mm@gmail.com
